/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'
import { Route as AuthenticatedAlimentacaoRouteImport } from './routes/_authenticated/alimentacao'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedHabitosRouteImport } from './routes/_authenticated/habitos'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedLembretesRouteImport } from './routes/_authenticated/lembretes'
import { Route as AuthenticatedMovimentoRouteImport } from './routes/_authenticated/movimento'
import { Route as AuthenticatedProgressoRouteImport } from './routes/_authenticated/progresso'
import { Route as AuthenticatedRotinaRouteImport } from './routes/_authenticated/rotina'
import { Route as AuthenticatedVivaAiRouteImport } from './routes/_authenticated/viva-ai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlimentacaoRoute =
  AuthenticatedAlimentacaoRouteImport.update({
    id: '/alimentacao',
    path: '/alimentacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHabitosRoute = AuthenticatedHabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLembretesRoute = AuthenticatedLembretesRouteImport.update({
  id: '/lembretes',
  path: '/lembretes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimentoRoute = AuthenticatedMovimentoRouteImport.update({
  id: '/movimento',
  path: '/movimento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressoRoute = AuthenticatedProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotinaRoute = AuthenticatedRotinaRouteImport.update({
  id: '/rotina',
  path: '/rotina',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVivaAiRoute = AuthenticatedVivaAiRouteImport.update({
  id: '/viva-ai',
  path: '/viva-ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/planos': typeof PlanosRoute
  '/quiz': typeof QuizRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/alimentacao': typeof AuthenticatedAlimentacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/lembretes': typeof AuthenticatedLembretesRoute
  '/movimento': typeof AuthenticatedMovimentoRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/rotina': typeof AuthenticatedRotinaRoute
  '/viva-ai': typeof AuthenticatedVivaAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/planos': typeof PlanosRoute
  '/quiz': typeof QuizRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/alimentacao': typeof AuthenticatedAlimentacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/lembretes': typeof AuthenticatedLembretesRoute
  '/movimento': typeof AuthenticatedMovimentoRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/rotina': typeof AuthenticatedRotinaRoute
  '/viva-ai': typeof AuthenticatedVivaAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/planos': typeof PlanosRoute
  '/quiz': typeof QuizRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/alimentacao': typeof AuthenticatedAlimentacaoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/habitos': typeof AuthenticatedHabitosRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/lembretes': typeof AuthenticatedLembretesRoute
  '/_authenticated/movimento': typeof AuthenticatedMovimentoRoute
  '/_authenticated/progresso': typeof AuthenticatedProgressoRoute
  '/_authenticated/rotina': typeof AuthenticatedRotinaRoute
  '/_authenticated/viva-ai': typeof AuthenticatedVivaAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/planos'
    | '/quiz'
    | '/admin'
    | '/ajustes'
    | '/alimentacao'
    | '/configuracoes'
    | '/habitos'
    | '/inicio'
    | '/lembretes'
    | '/movimento'
    | '/progresso'
    | '/rotina'
    | '/viva-ai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/planos'
    | '/quiz'
    | '/admin'
    | '/ajustes'
    | '/alimentacao'
    | '/configuracoes'
    | '/habitos'
    | '/inicio'
    | '/lembretes'
    | '/movimento'
    | '/progresso'
    | '/rotina'
    | '/viva-ai'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/planos'
    | '/quiz'
    | '/_authenticated/admin'
    | '/_authenticated/ajustes'
    | '/_authenticated/alimentacao'
    | '/_authenticated/configuracoes'
    | '/_authenticated/habitos'
    | '/_authenticated/inicio'
    | '/_authenticated/lembretes'
    | '/_authenticated/movimento'
    | '/_authenticated/progresso'
    | '/_authenticated/rotina'
    | '/_authenticated/viva-ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PlanosRoute: typeof PlanosRoute
  QuizRoute: typeof QuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alimentacao': {
      id: '/_authenticated/alimentacao'
      path: '/alimentacao'
      fullPath: '/alimentacao'
      preLoaderRoute: typeof AuthenticatedAlimentacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habitos': {
      id: '/_authenticated/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof AuthenticatedHabitosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lembretes': {
      id: '/_authenticated/lembretes'
      path: '/lembretes'
      fullPath: '/lembretes'
      preLoaderRoute: typeof AuthenticatedLembretesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimento': {
      id: '/_authenticated/movimento'
      path: '/movimento'
      fullPath: '/movimento'
      preLoaderRoute: typeof AuthenticatedMovimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progresso': {
      id: '/_authenticated/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof AuthenticatedProgressoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotina': {
      id: '/_authenticated/rotina'
      path: '/rotina'
      fullPath: '/rotina'
      preLoaderRoute: typeof AuthenticatedRotinaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/viva-ai': {
      id: '/_authenticated/viva-ai'
      path: '/viva-ai'
      fullPath: '/viva-ai'
      preLoaderRoute: typeof AuthenticatedVivaAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedAlimentacaoRoute: typeof AuthenticatedAlimentacaoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedHabitosRoute: typeof AuthenticatedHabitosRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedLembretesRoute: typeof AuthenticatedLembretesRoute
  AuthenticatedMovimentoRoute: typeof AuthenticatedMovimentoRoute
  AuthenticatedProgressoRoute: typeof AuthenticatedProgressoRoute
  AuthenticatedRotinaRoute: typeof AuthenticatedRotinaRoute
  AuthenticatedVivaAiRoute: typeof AuthenticatedVivaAiRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedAlimentacaoRoute: AuthenticatedAlimentacaoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedHabitosRoute: AuthenticatedHabitosRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedLembretesRoute: AuthenticatedLembretesRoute,
  AuthenticatedMovimentoRoute: AuthenticatedMovimentoRoute,
  AuthenticatedProgressoRoute: AuthenticatedProgressoRoute,
  AuthenticatedRotinaRoute: AuthenticatedRotinaRoute,
  AuthenticatedVivaAiRoute: AuthenticatedVivaAiRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PlanosRoute: PlanosRoute,
  QuizRoute: QuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
